---
booktitle: Proceedings of the 7th Machine Learning for Healthcare Conference
volume: '182'
shortname: MLHC
year: '2022'
start: 2022-08-05
end: 2022-08-06
published: 2022-12-31
url: https://proceedings.mlr.press
conference_number: '7'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLHC-2022
month: 0
cycles: false
bibtex_editor: Lipton, Zachary and Ranganath, Rajesh and Sendak, Mark and Sjoding,
  Michael and Yeung, Serena
editor:
- given: Zachary
  family: Lipton
- given: Rajesh
  family: Ranganath
- given: Mark
  family: Sendak
- given: Michael
  family: Sjoding
- given: Serena
  family: Yeung
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 7th Machine Learning for Healthcare Conference
    Held in 301 W Morgan St, Durham, NC 27701 on 05-06 August 2022

  Published as Volume 182 by the Proceedings of Machine Learning Research on 31 December 2022.

  Volume Edited by:
    Zachary Lipton
    Rajesh Ranganath
    Mark Sendak
    Michael Sjoding
    Serena Yeung

  Series Editors:
    Neil D. Lawrence
date_str: 05--06 Aug
author:
  name: PMLR
baseurl: "/v182"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v182
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v182
email: ''
conference:
  name: Machine Learning for Healthcare Conference
  url:
  location: 301 W Morgan St, Durham, NC 27701
  dates:
  - 2022-08-05
  - 2022-08-06
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v182/MLHC22-updated.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v182/MLHC22-updated.bib
